# Generated by Django 6.0.1 on 2026-04-03 23:24

import portfolio_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[portfolio_backend.validators.validate_image_file], verbose_name='Photo de profil'),
        ),
    ]
