# Generated by Django 6.0.1 on 2026-05-12 15:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='CV (PDF)'),
        ),
    ]
