# Generated by Django 6.0.1 on 2026-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
