# Generated by Django 6.0.1 on 2026-01-28 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('full_description', models.TextField(blank=True, verbose_name='Description complète')),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/', verbose_name='Image de couverture')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Séparées par des virgules (ex: Angular, Django, MySQL)', max_length=500, verbose_name='Technologies')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Lien démo')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('archived', 'Archivé')], default='completed', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Projet mis en avant')),
                ('order', models.IntegerField(default=0, help_text='Plus le nombre est petit, plus le projet apparaît en premier', verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
