# Generated by Django 6.0.1 on 2026-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vues'),
        ),
    ]
