# Generated by Django 6.0.1 on 2026-04-03 23:24

import portfolio_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[portfolio_backend.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[portfolio_backend.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[portfolio_backend.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/thumbnails/', validators=[portfolio_backend.validators.validate_image_file], verbose_name='Image de couverture'),
        ),
    ]
