# Generated by Django 6.0.1 on 2026-04-07 19:15

import portfolio_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image_1_alter_project_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/', validators=[portfolio_backend.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/', validators=[portfolio_backend.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/', validators=[portfolio_backend.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(max_length=255, upload_to='projects/thumbnails/', validators=[portfolio_backend.validators.validate_image_file], verbose_name='Image de couverture'),
        ),
    ]
