# Generated by Django 6.0.1 on 2026-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image_1_alter_project_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Projet mis en avant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text='Plus le nombre est petit, plus le projet apparaît en premier', verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('archived', 'Archivé')], db_index=True, default='completed', max_length=20, verbose_name='Statut'),
        ),
    ]
