# Generated by Django 6.0.3 on 2026-06-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_created_at_alter_project_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.TextField(blank=True, verbose_name='Contexte client'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, verbose_name='Résultat / Impact'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Problème à résoudre'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Solution apportée'),
        ),
    ]
