# Generated by Django 6.0.1 on 2026-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé')], db_index=True, default='new', max_length=20, verbose_name='Statut'),
        ),
    ]
