# Generated by Django 6.0.3 on 2026-06-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='mission_type',
            field=models.CharField(blank=True, choices=[('data', 'Data Engineering'), ('dev', 'Développement Full-Stack'), ('consulting', 'Consulting / Architecture'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Type de mission'),
        ),
    ]
