# Generated by Django 6.0.1 on 2026-04-03 23:24

import portfolio_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(upload_to='blog/featured/', validators=[portfolio_backend.validators.validate_image_file], verbose_name='Image de couverture'),
        ),
    ]
