# Generated by Django 6.0.1 on 2026-04-09 19:27

import portfolio_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(max_length=255, upload_to='blog/featured/', validators=[portfolio_backend.validators.validate_image_file], verbose_name='Image de couverture'),
        ),
    ]
