# Generated by Django 6.0.1 on 2026-01-28 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', 'Expérience professionnelle'), ('education', 'Formation'), ('certification', 'Certification')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Poste/Diplôme')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise/École')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/logos/', verbose_name='Logo entreprise')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date'],
            },
        ),
    ]
