# Generated by Django 6.0.1 on 2026-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='experience/certificates/', verbose_name='Certificat (PDF/image)'),
        ),
    ]
