# Generated by Django 6.0.1 on 2026-04-03 23:24

import portfolio_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experience_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='experience/certificates/', validators=[portfolio_backend.validators.validate_doc_or_image], verbose_name='Certificat (PDF/image)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='experience/logos/', validators=[portfolio_backend.validators.validate_image_file], verbose_name='Logo entreprise'),
        ),
    ]
