# Generated by Django 6.0.1 on 2026-04-09 19:27

import portfolio_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experience_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certificate_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='experience/certificates/', validators=[portfolio_backend.validators.validate_doc_or_image], verbose_name='Certificat (PDF/image)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='experience/logos/', validators=[portfolio_backend.validators.validate_image_file], verbose_name='Logo entreprise'),
        ),
    ]
