# Generated by Django 6.0.1 on 2026-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_alter_experience_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('work', 'Expérience professionnelle'), ('education', 'Formation'), ('certification', 'Certification')], db_index=True, max_length=20, verbose_name='Type'),
        ),
    ]
