# Generated by Django 6.0.3 on 2026-05-12 16:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_alter_experience_start_date_alter_experience_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certificate_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Certificat (PDF/image)'),
        ),
    ]
